### ISSUE TITLE
Incompatibilty of CAPS dependency in Zeppelin

### ISSUE THREAD

**Issue by abhi19gupta** [opencypher/cypher-for-apache-spark#196]
I was following the tutorial on using CAPS in Zeppelin ([Link](https://github.com/opencypher/cypher-for-apache-spark/wiki/Use-CAPS-in-a-Zeppelin-notebook)).

At the stage where it says:

> In the Dependencies section, add the path to the CAPS jar file

I used the path to the "caps-core-1.0-SNAPSHOT-standalone-shell.jar" which is present in caps-core/target. (Correct me if I am wrong in using this jar)

Before adding this dependency, Spark is working fine in Zeppelin i.e. the following gives no error in Zeppelin:

> %spark
sc.parallelize(0 to 9)

But after adding the dependency I am getting the following error on running the above code:

> java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.zeppelin.spark.SparkInterpreter.hiveClassesArePresent(SparkInterpreter.java:218)
	at org.apache.zeppelin.spark.SparkInterpreter.createSparkSession(SparkInterpreter.java:366)
	at org.apache.zeppelin.spark.SparkInterpreter.getSparkSession(SparkInterpreter.java:233)
	at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:841)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:491)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I am using Zeppelin-0.7.3 as mentioned in your tutorial and the spark interpreter is the default one that comes with it. I am using the latest version of Cypher-for-Apache-Spark (I cloned the repository 6 hours ago).

Any help would be greatly appreciated.

**Comment by DarthMax** [comment]
Hey there!
Thanks for notifying us about that issue. I have looked into it and the problem seems to be an incompatibility between the Spark and/or Scala version shipped with Zeppelin and the Spark and Scala versions contained inside the fat jar CAPS package. 
I was able to solve the problem by letting maven decide which packages and version to import, instead of  bundling all of the CAPS dependencies into a single jar.

We have update the example Zeppelin note and the install instructions here https://github.com/opencypher/cypher-for-apache-spark/wiki/Use-CAPS-in-a-Zeppelin-notebook . With the new example note it is not necessary any more to change the interpreter settings. Just make sure that CAPS is installed in your local maven repository (just run `mvn clean install -DskipTests` inside the CAPS folder)

It would be great if you could check out the new instructions and tell us if the problem persists.
Best, Max

**Comment by abhi19gupta** [comment]
Hey,
I just tried this. The problem that I am now facing is that I am behind a proxy network and hence `z.load("org.opencypher:cypher-for-apache-spark:1.0-SNAPSHOT")` fails with 'Connection Refused'.

I have tried to add proxy settings to the Zeppelin dependency manager but with no success. The following link hint that proxy doesn't seem to work with Zeppelin dependency manager ([Link 1](https://issues.apache.org/jira/browse/ZEPPELIN-169) [Link 2](https://stackoverflow.com/questions/45997061/cannt-download-spark-dependency-in-zeeplin-behind-a-proxy)) 

Is it possible in any other way?

**Comment by abhi19gupta** [comment]
To explicitly load dependency from local repo, we have to use something like
`z.load("/home/db0/.m2/repository/org/opencypher/cypher-for-apache-spark/1.0-SNAPSHOT/cypher-for-apache-spark-1.0-SNAPSHOT-standalone-shell.pom")`
When I did this, then the dependency loading seems to work fine with output:
`res0: org.apache.zeppelin.dep.Dependency = org.apache.zeppelin.dep.Dependency@25c868ae`

However, the line `import org.opencypher.caps.api.spark.{CAPSGraph, CAPSSession}` still fails with `error: object opencypher is not a member of package org`

**Comment by abhi19gupta** [comment]
Moreover, I cannot build Zeppelin with Spark 2.2.0 because they only support building with up to Spark 2.1.
[(Link)](https://zeppelin.apache.org/docs/0.7.3/install/build.html#build-profiles).
Is it possible to not use Zeppelin and work directly with Spark?

**Comment by DarthMax** [comment]
I am not sure about referencing the pom file. https://zeppelin.apache.org/docs/0.7.3/interpreter/spark.html#3-dynamic-dependency-loading-via-sparkdep-interpreter only states either jars or the maven artifact.

You can try building the current development version of Zeppelin 0.8.0, which adds support for Spark 2.2.0. I have done that successfully several times following these directions: https://zeppelin.apache.org/docs/0.8.0-SNAPSHOT/setup/basics/how_to_build.html#how-to-build-zeppelin-from-source

However you can also use CAPS in any standalone Spark application. Just  install CAPS into your local maven repository and then add the following dependency to your pom `dependencies` section:

```
        <dependency>
            <groupId>org.opencypher</groupId>
            <artifactId>cypher-for-apache-spark</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
```

Then you can start building your Spark application. You can find an example here: https://github.com/opencypher/cypher-for-apache-spark#hello-caps

**Comment by abhi19gupta** [comment]
It worked! As you suggested, I built Zeppelin 0.8 from source using Spark 2.2.0 and Scala 2.11. Then I could successfully add the dependency `caps-core-1.0-SNAPSHOT-standalone-shell.jar` (by using local file path) to Zeppelin' Spark interpreter, as explained in your earlier tutorial.

I would suggest you add this method back to your tutorials (as an alternative method), just in case z.load(...) doesn't work for someone, as it happened to me. Thanks a lot for your time!
