### ISSUE TITLE
SessionGraphSource not serializable

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#390]
Issue reported following the below steps:

```
scala> import org.opencypher.spark.api.CAPSSession
import org.opencypher.spark.api.CAPSSession

scala> implicit val session: CAPSSession = CAPSSession.create()(spark)
session: org.opencypher.spark.api.CAPSSession = CAPSSessionImpl

scala> val df = spark.read.format("csv").option("header", "true").option("inferSchema", "true").load("hdfs://192.168.42.191/data/retail-data/by-day/2010-12-01.csv")
df: org.apache.spark.sql.DataFrame = [InvoiceNo: string, StockCode: string ... 6 more fields]

scala> val udfExampleDF = spark.range(5).toDF("num")
udfExampleDF: org.apache.spark.sql.DataFrame = [num: bigint]

scala> def power3 (number:Double):Double = number * number * number
power3: (number: Double)Double

scala> power3(2.0)
res1: Double = 8.0

scala> import org.apache.spark.sql.functions.udf
import org.apache.spark.sql.functions.udf

scala> val power3udf = udf(power3(_:Double):Double)
power3udf: org.apache.spark.sql.expressions.UserDefinedFunction = UserDefinedFunction(<function1>,DoubleType,Some(List(DoubleType)))

scala> udfExampleDF.select(power3udf(col("num"))).show()
org.apache.spark.SparkException: Task not serializable
  at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:340)
  at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:330)
  at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:156)
  at org.apache.spark.SparkContext.clean(SparkContext.scala:2294)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1.apply(RDD.scala:841)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1.apply(RDD.scala:840)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.mapPartitionsWithIndex(RDD.scala:840)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:389)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:228)
  at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:311)
  at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:2861)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2150)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2150)
  at org.apache.spark.sql.Dataset$$anonfun$55.apply(Dataset.scala:2842)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:2841)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2150)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2363)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:241)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:637)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:596)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:605)
  ... 48 elided
Caused by: java.io.NotSerializableException: org.opencypher.okapi.impl.io.SessionGraphDataSource
Serialization stack:
    - object not serializable (class: org.opencypher.okapi.impl.io.SessionGraphDataSource, value: org.opencypher.okapi.impl.io.SessionGraphDataSource@175957f9)
    - field (class: scala.collection.immutable.Map$Map1, name: value1, type: class java.lang.Object)
    - object (class scala.collection.immutable.Map$Map1, Map(session -> org.opencypher.okapi.impl.io.SessionGraphDataSource@175957f9))
    - field (class: org.opencypher.spark.impl.CAPSSessionImpl, name: dataSourceMapping, type: interface scala.collection.immutable.Map)
    - object (class org.opencypher.spark.impl.CAPSSessionImpl, CAPSSessionImpl)
    - field (class: $iw, name: session, type: interface org.opencypher.spark.api.CAPSSession)
    - object (class $iw, $iw@70de1e65)
    - field (class: $iw, name: $iw, type: class $iw)
    - object (class $iw, $iw@f0ead61)
    - field (class: $iw, name: $iw, type: class $iw)
    - object (class $iw, $iw@339ecd3f)
    - field (class: $iw, name: $iw, type: class $iw)
    - object (class $iw, $iw@49bc9588)
    - field (class: $iw, name: $iw, type: class $iw)
    - object (class $iw, $iw@16454a28)
    - field (class: $iw, name: $iw, type: class $iw)
    - object (class $iw, $iw@1b9b8759)
    - field (class: $iw, name: $iw, type: class $iw)
    - object (class $iw, $iw@281e2377)
    - field (class: $iw, name: $iw, type: class $iw)
    - object (class $iw, $iw@eb2ce99)
    - field (class: $line16.$read, name: $iw, type: class $iw)
    - object (class $line16.$read, $line16.$read@d476a21)
    - field (class: $iw, name: $line16$read, type: class $line16.$read)
    - object (class $iw, $iw@2d739a6f)
    - field (class: $iw, name: $outer, type: class $iw)
    - object (class $iw, $iw@11a3ffe6)
    - field (class: $anonfun$1, name: $outer, type: class $iw)
    - object (class $anonfun$1, <function1>)
    - field (class: org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2, name: func$2, type: interface scala.Function1)
    - object (class org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2, <function1>)
    - field (class: org.apache.spark.sql.catalyst.expressions.ScalaUDF, name: f, type: interface scala.Function1)
    - object (class org.apache.spark.sql.catalyst.expressions.ScalaUDF, UDF(cast(input[0, bigint, false] as double)))
    - element of array (index: 1)
    - array (class [Ljava.lang.Object;, size 2)
    - field (class: org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8, name: references$1, type: class [Ljava.lang.Object;)
    - object (class org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8, <function2>)
  at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
  at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
  at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
  at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:337)
  ... 79 more
```

**Comment by Mats-SX** [comment]
@tomgeudens If you declare the `CAPSSession` as not `implicit` but just a normal `val`, you can work around this issue. Apparently Spark tries to clean the `udf` for serialisation, and considers `implicit` variables to constitute part of the function body by default, thus tries to serialise the `CAPSSession`.

This is a bit unexpected behaviour from Spark -- we never wanted to include the `CAPSSession` in the serialised function it tries to send across the cluster, but we don't know how to exclude it right now.

**Comment by tomgeudens** [comment]
@Mats-SX Workaround confirmed (and glad I could point out a bit of **unexpected behaviour**

**Comment by tomgeudens** [comment]
@Mats-SX I just found out the workaround doesn't actually work because our own stuff seems to require the CAPSSession to be implicit : 
cala> spark.conf.set("spark.sql.shuffle.partitions","5")

scala> import org.opencypher.spark.api.CAPSSession
import org.opencypher.spark.api.CAPSSession

scala> val session: CAPSSession = CAPSSession.local()
2018-05-07 12:49:02 WARN  SparkSession$Builder:66 - Using an existing SparkSession; some configuration may not take effect.
session: org.opencypher.spark.api.CAPSSession = CAPSSessionImpl

scala> import java.net.URI
import java.net.URI

scala> val fileURI: URI = new URI("file:///home/tomgeudens/data/movies")
fileURI: java.net.URI = file:///home/tomgeudens/data/movies

scala> import org.opencypher.spark.impl.io.hdfs.CsvGraphLoader
import org.opencypher.spark.impl.io.hdfs.CsvGraphLoader

scala> val loader = CsvGraphLoader(fileURI)
<console>:28: error: could not find implicit value for parameter caps: org.opencypher.spark.api.CAPSSession
       val loader = CsvGraphLoader(fileURI)

**Comment by pstutz** [comment]
A better workaround would be:
```
object CleanFunctions {
  def power3(number: Double): Double = number * number * number
}
```

This way serialising the function cannot capture anything that it shouldn't.

Co-Authored-By: Max Kießling <max.kiessling@neotechnology.com>
