### ISSUE TITLE
Investigate flaky builds due to StackoverflowException in Typer

### ISSUE THREAD

**Issue by s1ck** [opencypher/cypher-for-apache-spark#478]
builds fail quite often due to 
```
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:712)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5492)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.typedLabelDef(Typers.scala:2291)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5361)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5380)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:712)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5481)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3042)
[22:17:49][org.opencypher:spark-cypher] 	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
```

**Comment by s1ck** [comment]
According to Travis and TC, the error started happening after https://github.com/opencypher/cypher-for-apache-spark/pull/433 was merged. Maybe we should have a second look at that PR and the ones before.

**Comment by pstutz** [comment]
I first saw it in that PR and tried to increase the stack size. It's really weird, because I don't see any particularly fancy type inference being used in that PR. Would probably help to get debug logging from the compiler so we know what class is being compiled when the typer goes down a rabbit hole.

**Comment by pstutz** [comment]
My first guess otherwise would have been something like the `-Ypartial-unification` scalac param.

**Comment by pstutz** [comment]
I think `-Ytyper-debug` might be helpful.

**Comment by pstutz** [comment]
If it's [this](https://issues.scala-lang.org/browse/SI-9696) error, then simply further increasing the stack size might help.

**Comment by pstutz** [comment]
I suspect it's related to the shapeless magic used when inferring case class serialiser. I suggest we simplify `SchemaImpl` to no longer contain the wrapper classes around maps. From there I'd like to try using uJson /uPickle case class serialisation (with the removed wrappers that should look the same).

**Comment by s1ck** [comment]
The build log on TC also points into that direction. The last repeating output is the following:
```
$web$JsonSerialiser$$anonfun$$$outer in $anonfun) implicits disabled
[16:49:00]W:             [org.opencypher:spark-cypher] |    |    |    \-> org.opencypher.spark.web.JsonSerialiser.$anonfun.type (with underlying type scala.runtime.AbstractFunction1[String,io.circe.Json] with Serializable{val $outer(): JsonSerialiser.this.type})
[16:49:00]W:             [org.opencypher:spark-cypher] |    |    \-> this.$outer.type (with underlying type org.opencypher.spark.web.JsonSerialiser)
[16:49:00]W:             [org.opencypher:spark-cypher] |    \-> [def org$opencypher$spark$web$JsonSerialiser$$anonfun$$$outer] ()JsonSerialiser.this.type (with underlying type ()JsonSerialiser.this.type)
[16:49:00]W:             [org.opencypher:spark-cypher] |-- def org$opencypher$spark$web$JsonSerialiser$$anonfun$$$ou... EXPRmode (site: anonymous class $anonfun) implicits disabled
[16:49:00]W:             [org.opencypher:spark-cypher] |    |-- JsonSerialiser.this.type : pt=JsonSerialiser.this.type EXPRmode (site: value org$opencypher$spark$web$JsonSerialiser$$anonfun$$$outer in $anonfun) implicits disabled
[16:49:00]W:             [org.opencypher:spark-cypher] |    |    |-- scala.runtime.AbstractFunction1[String,io.circe.Json] wit... EXPRmode-POLYmode-QUALmode (site: value org$opencypher$spark$web$JsonSerialiser$$anonfun$$$outer in $anonfun) implicits disabled
[16:49:00]W:             [org.opencypher:spark-cypher] |    |    |    \-> org.opencypher.spark.web.JsonSerialiser.$anonfun.type (with underlying type scala.runtime.AbstractFunction1[String,io.circe.Json] with Serializable{val $outer(): JsonSerialiser.this.type})
[16:49:00]W:             [org.opencypher:spark-cypher] |    |    \-> this.$outer.type (with underlying type org.opencypher.spark.web.JsonSerialiser)
[16:49:00]W:             [org.opencypher:spark-cypher] |    \-> [def org$opencypher$spark$web$JsonSerialiser$$anonfun$$$outer] ()JsonSerialiser.this.type (with underlying type ()JsonSerialiser.this.type)
```

**Comment by DarthMax** [comment]
Fixed by https://github.com/opencypher/cypher-for-apache-spark/pull/479
