### ISSUE TITLE
error on build on Ubuntu(18)

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#566]
as it dosen't work on windows and since you mentionned that Linux and Appel environment should work without problem.
i retried the `mvn clean install` on ubuntu 18 and now i get this error : 

- unsupported uses of lists of children *** FAILED ***
  "...on-child type: java.[base/java.]lang.String cannot b..." did not equal "...on-child type: java.[]lang.String cannot b..." (TreeNodeTest.scala:89)
  org.scalatest.exceptions.TestFailedException:
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
      at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6716)
      at org.opencypher.okapi.trees.TreeNodeTest$$anonfun$10.apply(TreeNodeTest.scala:89)
      at org.opencypher.okapi.trees.TreeNodeTest$$anonfun$10.apply(TreeNodeTest.scala:68)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
     at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
     at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
     at org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
     at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:451)
     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
     at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:464)
     at org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
     at scala.collection.immutable.List.foreach(List.scala:392)
     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
       at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:497)
     at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
     at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
      at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
  ......

**Comment by pstutz** [comment]
I created a PR to remove the part that seems to be JVM specific from the expected test output. What JVM version are you running on Ubuntu? To make sure we have no JVM-specific dependencies we should run CI against a setup similar to what you use.

**Comment by HADDADENICAR** [comment]
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

**Comment by DarthMax** [comment]
We currently do not support JDK versions other than JDK 8. I think that might have caused the errors you saw

**Comment by HADDADENICAR** [comment]
You re right , i deleted the version 10 and re-installed the JDK 8. and now the `mvn clean install` success for the first time : 
    
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summ ary:
    [INFO] 
    [INFO] Okapi - openCypher query compilation API and pipeline SUCCESS [ 13.109 s]
    [INFO] Okapi Trees - Tree rewriting framework for Okapi ... SUCCESS [01:21 min]
    [INFO] Okapi - openC ypher API ............................. SUCCESS [03:05 min]
    [INFO] Okapi Test Utilities ............................... SUCCESS [12:34 min]
    [INFO] Okapi IR - Declarative representation of Cypher queries SUCCESS [06:43 min]
    [INFO] Okapi - Neo4j procedures ........................... SUCCESS [01:59 min]
    [INFO] Okapi Logical - Logical representation of Cypher queries SUCCESS [02:43 min]
    [INFO] Okapi Relational - Relational Algebra for Cypher ... SUCCESS [02:48 min]
    [INFO] Okapi TCK - TCK integration for the Okapi pipeline . SUCCESS [04:25 min]
    [INFO] Cypher for Apache Spark - CAPS ..................... SUCCESS [03:08 min]
    [INFO] Cypher for Apache Spark - Test Utilities ........... SUCCESS [  01:05 h]
    [INFO] Collection of examples for Cypher for Apache Spark . SUCCESS [09:59 min]
    [INFO] Cypher for Apache Spark - TCK ...................... SUCCESS [15:12 min]
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 02:10 h
    [INFO] Finished at: 2018-07-24T23:52:11+01:00
    [INFO] Final Memory: 102M/598M
    [INFO] ------------------------------------------------------------------------
