### ISSUE TITLE
How to connect to and store into neo4j with last release

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#627]
previously i was connecting to neo4j using this code:

      //12)  Connect to Neo4j
        val boltWriteURI: URI = new URI("bolt://localhost:7687")
        val neo4jWriteConfig: Neo4jConfig = new Neo4jConfig(boltWriteURI, "neo4j", Some("my_password"), true)
        val neo4jResult: Neo4jPropertyGraphDataSource = new Neo4jPropertyGraphDataSource(neo4jWriteConfig)(session)

And then storing the graph  : 

     //13) Store graph in neo4j
        val neo4jResultName: GraphName = new GraphName("neo4jgraphs154")
        neo4jResult.store(neo4jResultName, graph)

However this code is not working any more for me, so i am asking if you have changed  in it ?

**Comment by DarthMax** [comment]
Could you be a bit more specific about the error that occurs.

**Comment by HADDADENICAR** [comment]
I got connection Timeout error,although the neo4j service is running :

     Exception in thread "main" org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Unable to establish connection in 5000ms
	   at org.neo4j.driver.internal.async.inbound.ConnectTimeoutHandler.unableToConnectError(ConnectTimeoutHandler.java:55)
	   at org.neo4j.driver.internal.async.inbound.ConnectTimeoutHandler.readTimedOut(ConnectTimeoutHandler.java:49)
	   at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:90)
	   at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:494)
	   at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:466)
	   at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	   at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	   at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	   at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	   at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	   at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	   at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	   at java.lang.Thread.run(Thread.java:748)

**Comment by HADDADENICAR** [comment]
I figured out what is the  problem ; the problem comes from  the `mergeGraph` that i try to create from my `intialgraph`.

        session.catalog.store("inputGraph", graph)
        session.cypher ("""
        CATALOG CREATE GRAPH nodes {
        FROM session.inputGraph
        MATCH (x:HashNode)
        WITH DISTINCT x._c20 AS PickupValue
        CONSTRUCT
        CREATE (n:HashNode)
        SET n._c20 = PickupValue
        RETURN GRAPH
        }"""
      .stripMargin)
      val mergeGraph = session.cypher("""
                                    |FROM nodes
                                    |MATCH (x:HashNode)
                                    |FROM session.inputGraph
                                    |MATCH (y:HashNode)-[r]->(other)
                                    |WHERE y._c20 = x._c20
                                    |CONSTRUCT ON nodes
                                    |  CREATE (x)-[COPY OF r]->(COPY OF other)
                                    |RETURN GRAPH
                                  """.stripMargin).graph




when i store in Neo4j the intial graph i didn't get errors , but i still don't know why this happen with **mergeGraph** !

**Comment by HADDADENICAR** [comment]
solved the problem was a *syntax problem*  a space is added before stripMargin which created the issue
