### ISSUE TITLE
Improve error message when calling `tail()` on an empty list

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#632]
trying to apply `tail()` method on a list ,the list is created with `collect()` ,i get the following error  : 

     Exception in thread "main" scala.MatchError: Tail (of class org.opencypher.v9_0.expressions.functions.Tail$)
	at org.opencypher.okapi.ir.impl.typer.SchemaTyper$BasicSignatureBasedTyper$.generateSignaturesFor(SchemaTyper.scala:480)
	at org.opencypher.okapi.ir.impl.typer.SchemaTyper$SignatureBasedInvocationTyper$class.selectSignaturesFor(SchemaTyper.scala:454)
	at org.opencypher.okapi.ir.impl.typer.SchemaTyper$BasicSignatureBasedTyper$.selectSignaturesFor(SchemaTyper.scala:475)
	at org.opencypher.okapi.ir.impl.typer.SchemaTyper$SignatureBasedInvocationTyper$$anonfun$apply$53$$anonfun$apply$55$$anonfun$apply$56.apply(SchemaTyper.scala:438)
	at org.opencypher.okapi.ir.impl.typer.SchemaTyper$SignatureBasedInvocationTyper$$anonfun$apply$53$$anonfun$apply$55$$anonfun$apply$56.apply(SchemaTyper.scala:437)
	at org.atnos.eff.EffImplicits$$anon$1$$anonfun$flatMap$1.apply(Eff.scala:181)
	at org.atnos.eff.EffImplicits$$anon$1$$anonfun$flatMap$1.apply(Eff.scala:181)
         .....
these is my code :
    
      FROM GRAPH nodes
      match(m)
      FROM GRAPH session.inputGraph
       match(n) where n.geohash=m.geohash
       with  collect(n.timehash)as timehashList
       WITH tail(timehashList)  AS result
       construct
       create(h:hashnode{timehashList:result)
     RETURN GRAPH

**Comment by Mats-SX** [comment]
`tail()` is not implemented. We should improve the error message.
