### ISSUE TITLE
SqlGraphSource runtime json error on spark cluster using Spark Cloudera 2.2.0

### ISSUE THREAD

**Issue by DarthMax** [opencypher/cypher-for-apache-spark#678]
By @hannesmiller 
On our newly provisioned `Cloudera certification cluster` I encountered the following runtime error:

```
Exception in thread "main" org.json4s.package$MappingException: No usable value for caseSensitive
Did not find value which can be converted into boolean
	at org.json4s.reflect.package$.fail(package.scala:96)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:462)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$instantiate(Extraction.scala:470)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:515)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:512)
	at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:524)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:512)
	at org.json4s.Extraction$.extract(Extraction.scala:351)
	at org.json4s.Extraction$.extract(Extraction.scala:42)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at org.neo4j.sql.jdbc.parser.SqlDataSourcesParser$$anonfun$fromString$1.apply(SqlDataSourcesParser.scala:32)
	at org.neo4j.sql.jdbc.parser.SqlDataSourcesParser$$anonfun$fromString$1.apply(SqlDataSourcesParser.scala:31)
```

The class `SqlDataSourcesParse` is having difficulty parsing the `hive-data-sources.json` file - this is not a problem on `local` `IntelliJ` session.  

It seems though that the `json4s` library is not able to handle a case class defined as follows:
```scala
  case class SQLDataSource(
    storageFormat: String, // Currently supports hive or jdbc
    dataSourceName: String, // The name of the data source
    schemaName: Option[String] = None, // Some DBMS systems call this database and others the user schema (can be omitted, e.g. use the default schema/database)
    catalogName: Option[String] = None,
    graphContainer: Option[String] = None,
    jdbcUri: Option[String] = None,
    jdbcDriver: Option[String] = None,
    jdbcDialect: Option[String] = Some("generic"), // can be generic
    jdbcFetchSize: Option[Int] = Some(100),
    caseSensitive: Boolean = false,
    kerberosPrincipal: Option[String] = None,
    kerberosKeytabFile: Option[String] = None,
    isDefaultEnvironment: Boolean = false
  )
```

Note: The exception suggests its not able to handle a `boolean` with a default argument??

- Using `Spark Cloudera 2.2.0`
- Morpheus jar: `morpheus-bundle-1.0.0-EAP0.jar`
- My application jar which just has a main:
```scala
object TPCHQueryFromSqlHivePGDSBug extends App {

  if (args.length != 4) {
    println(s"USAGE: ${getClass.getSimpleName.replace("$", "")} <spark master: local[*]|yarn> <graph root> <graph ddl file> <sql datasource file>")
    System.exit(1)
  }

  val sparkMaster = args(0)
  val graphRoot = args(1)
  val graphDDLFile = args(2)
  val dataSourceFile = args(3)

  // Create CAPS session
  implicit val sparkSession: SparkSession = SparkGateway(sparkMaster, enableHive = true)
  implicit val session: CAPSSession = CAPSSession.create

  // Register a SQL source (for Hive) in the Cypher session
  val graphName = "TPCH_2018"

  // JSON file config doesn't work on Cloudera/Spark 2.2.0? So temporarily hard-coding the config
  val sqlGraphSource = MorpheusGraphSource.sql(
    rootDirectoryPath = Paths.get(graphRoot),
    graphSchemaDDLFile = graphDDLFile,
    graphSQLDataSourcesFile = dataSourceFile)
  session.registerSource(Namespace("sql"), sqlGraphSource)

  // Access the graph via its qualified graph name
  val tpch = session.catalog.graph("sql." + graphName)

  // Run a simple Cypher query
  tpch.cypher(
    s"""
       |FROM GRAPH sql.$graphName
       |MATCH (n:Customer)-[r:CUSTOMER_FROM]->(m)
       |RETURN n,r,m
       |LIMIT 10
    """.stripMargin)
    .getRecords
    .show

  System.exit(0)
}

```

- gateway server login: ```ssh -i "neo4j-cdh-cert.pem" ec2-user@ec2-35-178-132-6.eu-west-2.compute.amazonaws.com```
- directory: ```cd /home/ec2-user/hive_sql_bug/certification-1.0-SNAPSHOT```
- command to run: ```bin/queryFromHiveSqlBug.sh yarn ./graph_ddl tpch.sql hive-data-sources.json```

**Comment by DarthMax** [comment]
By @hannesmiller 
Specifying the config `caseSensitive` boolean resolved the isssue, e.g.

From:
```
[
  {
    "storageFormat": "hive",
    "dataSourceName": "TPCH",
    "schemaName": "tpch_parquet",
    "isDefaultEnvironment": true
  }
]
```
To:
```
[
  {
    "storageFormat": "hive",
    "dataSourceName": "TPCH",
    "schemaName": "tpch_parquet",
    "caseSensitive": false,
    "isDefaultEnvironment": true
  }
]
```
This stems from the fact that the `json4s` has a problem with default arguments on the underlying case class some how - maybe its an ordering issue?

**Comment by Mats-SX** [comment]
I believe we switched to another JSON parsing library a while ago, didn't we?

Also there isn't a boolean field in that class anymore. I say we close this.
